"""
USSD session request and response schemas.

Architecture note — the platform is an orchestration layer, not a menu engine:

USSDAdvanceRequest carries next_step and response_text FROM the client.
The client application owns the menu logic and computes:
  - which step the session advances to (next_step)
  - what text to show the user (response_text)
The platform records the state transition and enforces TTL.
This design supports arbitrary USSD application logic without requiring
menu configuration to be stored on the platform.

response_text limit:
  GSMA USSD specification: maximum 182 characters per response page.
  Longer responses are truncated by the carrier — enforced here to
  prevent silent truncation in production.

session_id:
  A 32-character hex string (secrets.token_hex(16)) generated by
  USSDService.start_session(). Distinct from the PostgreSQL UUID primary key.
  Only session_id is exposed to USSD gateways and clients.

expires_at:
  Included in USSDSessionResponse so clients can display countdown timers
  and avoid sending advance requests to expired sessions.
"""
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.schemas.common import ApiMeta, PaginatedResponse, PaginationMeta

# GSMA USSD specification maximum per response page
_USSD_RESPONSE_MAX_CHARS: int = 182
# Maximum user input length — typical USSD gateway limit
_USSD_INPUT_MAX_CHARS: int = 20
# session_id is secrets.token_hex(16) = 32 hex chars
_SESSION_ID_LENGTH: int = 32


# ── Request Schemas ────────────────────────────────────────────────────────

class USSDStartRequest(BaseModel):
    """
    Request body for POST /ussd/start.

    Initiates a new USSD session. The platform creates:
      1. A Redis state entry (TTL: 180 seconds)
      2. A PostgreSQL USSDSession record (audit trail)

    msisdn: the subscriber initiating the USSD session.
            Accepted in any reasonable format — normalised to E.164 by
            the service layer (not validated here to keep schemas free
            of service-layer dependencies).

    service_code: the USSD short code that triggered the session
                  (e.g. '*144#'). Stored for audit and analytics only.

    initial_step: the step name to begin at. Defaults to 'MAIN_MENU'.
                  The platform does not interpret this — it is the
                  client's own step identifier.
    """
    model_config = ConfigDict(str_strip_whitespace=True)

    msisdn: str = Field(
        description="Subscriber MSISDN initiating the session (any format)"
    )
    service_code: str = Field(
        max_length=20,
        description="USSD service code that triggered this session (e.g. '*144#')",
    )
    initial_step: str = Field(
        default="MAIN_MENU",
        max_length=100,
        description="Starting step name (client-defined identifier)",
    )

    @field_validator("msisdn")
    @classmethod
    def validate_msisdn_non_empty(cls, v: str) -> str:
        if not v:
            raise ValueError("msisdn cannot be empty")
        return v

    @field_validator("service_code")
    @classmethod
    def validate_service_code(cls, v: str) -> str:
        if not v.startswith("*") and not v.startswith("#"):
            raise ValueError(
                "service_code must begin with '*' or '#' "
                "(e.g. '*144#', '#123*00#')"
            )
        return v


class USSDAdvanceRequest(BaseModel):
    """
    Request body for POST /ussd/respond.

    Advances an active session by one step.

    The client application is responsible for:
      - Computing which step to advance to (next_step)
      - Computing the text response to show the user (response_text)
      - Deciding whether the session should continue or end

    The platform is responsible for:
      - Verifying the session is still alive in Redis
      - Resetting the Redis TTL to 180 seconds
      - Recording the state transition in PostgreSQL
      - Returning the updated session state

    response_text is bounded at 182 characters per the GSMA USSD spec.
    Carrier equipment may silently truncate longer responses — enforcing
    here prevents silent data loss in production.
    """
    model_config = ConfigDict(str_strip_whitespace=True)

    session_id: str = Field(
        description="Session identifier returned by POST /ussd/start"
    )
    user_input: str = Field(
        max_length=_USSD_INPUT_MAX_CHARS,
        description="Digit(s) the subscriber pressed (e.g. '1', '2', '00')",
    )
    next_step: str = Field(
        max_length=100,
        description="Step identifier to advance to (client-defined)",
    )
    response_text: str = Field(
        max_length=_USSD_RESPONSE_MAX_CHARS,
        description=(
            f"Text to display to the subscriber (max {_USSD_RESPONSE_MAX_CHARS} "
            f"characters per GSMA USSD specification)"
        ),
    )
    session_data: dict | None = Field(
        default=None,
        description="Optional key-value pairs to merge into the session state",
    )

    @field_validator("session_id")
    @classmethod
    def validate_session_id_format(cls, v: str) -> str:
        """
        Validate session_id is a 32-character hex string.

        USSDService generates session_ids via secrets.token_hex(16)
        which always produces 32 lowercase hex characters.
        Reject clearly malformed session_ids before touching Redis or DB.
        """
        if len(v) != _SESSION_ID_LENGTH:
            raise ValueError(
                f"session_id must be {_SESSION_ID_LENGTH} characters. "
                f"Got {len(v)} characters."
            )
        if not all(c in "0123456789abcdefABCDEF" for c in v):
            raise ValueError(
                "session_id must contain only hexadecimal characters (0-9, a-f)"
            )
        return v.lower()  # normalise to lowercase

    @field_validator("response_text")
    @classmethod
    def validate_response_text_non_empty(cls, v: str) -> str:
        if not v:
            raise ValueError("response_text cannot be empty")
        return v


class USSDEndRequest(BaseModel):
    """
    Request body for DELETE /ussd/{session_id} (explicit session termination).

    Only session_id is needed — it is provided as a path parameter on the
    route, not in the request body. This schema is included for documentation
    completeness and potential future request body fields.
    """
    model_config = ConfigDict(frozen=True)


# ── Response Schemas ───────────────────────────────────────────────────────

class USSDSessionResponse(BaseModel):
    """
    Serialised USSD session state.

    Returned by:
      POST /ussd/start    → newly created session (state=ACTIVE)
      POST /ussd/respond  → updated session after step advance
      GET  /ussd/{id}     → current session state

    session_id: the externally visible identifier (32-char hex).
                The PostgreSQL UUID primary key is never exposed.

    expires_at: ISO 8601 timestamp when the session will expire.
                After this time, advance requests will return 410 Gone.
                Clients may use this to display a countdown timer.

    state: ACTIVE, ENDED, or TIMEOUT.
           ACTIVE: session is alive in Redis and can be advanced.
           ENDED:  explicitly terminated by client.
           TIMEOUT: expired without explicit termination.
    """
    model_config = ConfigDict(from_attributes=True)

    session_id: str
    msisdn: str
    service_code: str | None
    current_step: str
    state: str
    is_sandbox: bool
    created_at: str
    expires_at: str | None

    @classmethod
    def from_orm(cls, session) -> "USSDSessionResponse":
        """Build from USSDSession ORM instance."""
        return cls(
            session_id=session.session_id,
            msisdn=session.msisdn,
            service_code=getattr(session, "service_code", None),
            current_step=session.current_step,
            state=session.state.value if hasattr(session.state, "value") else str(session.state),
            is_sandbox=session.is_sandbox,
            created_at=session.created_at.isoformat() if session.created_at else "",
            expires_at=session.expires_at.isoformat() if session.expires_at else None,
        )


class USSDHistoryResponse(BaseModel):
    """
    Paginated USSD session history for GET /ussd/history.

    Usage in route handler:
        items, total = await ussd_svc.list_sessions(skip=skip, limit=limit)
        paginated = paginate(items, total, params)
        return USSDHistoryResponse.from_service(
            items=items, paginated=paginated,
            request_id=request.state.request_id,
        )
    """
    model_config = ConfigDict(frozen=True)

    success: bool = True
    items: list[USSDSessionResponse]
    pagination: PaginationMeta
    meta: ApiMeta

    @classmethod
    def from_service(
        cls,
        items: list,
        *,
        paginated,
        request_id: str,
    ) -> "USSDHistoryResponse":
        return cls(
            items=[USSDSessionResponse.from_orm(s) for s in items],
            pagination=PaginationMeta.from_paginated_result(paginated),
            meta=ApiMeta.build(request_id),
        )