"""add payment composite index

Revision ID: 7612bc16595f
Revises: f82745387fe4
Create Date: 2026-02-21 16:36:27.039874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7612bc16595f'
down_revision: Union[str, None] = 'f82745387fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_payment_app_status_created', 'payment_transactions', ['application_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_app_status_created', table_name='payment_transactions')
    # ### end Alembic commands ###
