"""add notification_records and number_verifications tables

Revision ID: a3bed7802989
Revises: c926ade31a29
Create Date: 2026-02-21 19:13:36.055785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bed7802989'
down_revision: Union[str, None] = 'c926ade31a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'PUSH', name='notificationchannel'), nullable=False),
    sa.Column('recipient', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['client_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_notification_app_channel_status', 'notification_records', ['application_id', 'channel', 'status'], unique=False)
    op.create_index(op.f('ix_notification_records_application_id'), 'notification_records', ['application_id'], unique=False)
    op.create_index(op.f('ix_notification_records_status'), 'notification_records', ['status'], unique=False)
    op.create_table('number_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('raw_input', sa.String(length=30), nullable=False),
    sa.Column('msisdn_e164', sa.String(length=20), nullable=True),
    sa.Column('country_hint', sa.String(length=2), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('operator', sa.Enum('ORANGE', 'FREE', 'EXPRESSO', 'UNKNOWN', name='operatorenum'), nullable=False),
    sa.Column('line_type', sa.Enum('MOBILE', 'FIXED', 'VOIP', 'UNKNOWN', name='linetype'), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('national_format', sa.String(length=30), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['client_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_number_app_operator', 'number_verifications', ['application_id', 'operator'], unique=False)
    op.create_index(op.f('ix_number_verifications_application_id'), 'number_verifications', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_number_verifications_application_id'), table_name='number_verifications')
    op.drop_index('ix_number_app_operator', table_name='number_verifications')
    op.drop_table('number_verifications')
    op.drop_index(op.f('ix_notification_records_status'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_application_id'), table_name='notification_records')
    op.drop_index('ix_notification_app_channel_status', table_name='notification_records')
    op.drop_table('notification_records')
    # ### end Alembic commands ###
