"""add ussd composite indexes

Revision ID: c926ade31a29
Revises: 7612bc16595f
Create Date: 2026-02-21 17:00:24.461131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c926ade31a29'
down_revision: Union[str, None] = '7612bc16595f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ussd_app_state_created', 'ussd_sessions', ['application_id', 'state', 'created_at'], unique=False)
    op.create_index('ix_ussd_state_expires', 'ussd_sessions', ['state', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ussd_state_expires', table_name='ussd_sessions')
    op.drop_index('ix_ussd_app_state_created', table_name='ussd_sessions')
    # ### end Alembic commands ###
