"""add sms composite index

Revision ID: f82745387fe4
Revises: 4a60d3480930
Create Date: 2026-02-21 16:18:13.814772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82745387fe4'
down_revision: Union[str, None] = '4a60d3480930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sms_app_status_created', 'sms_messages', ['application_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sms_app_status_created', table_name='sms_messages')
    # ### end Alembic commands ###
